### ISSUE TITLE
Non existent link to GenStage.async_notify/2 in docs

### ISSUE THREAD

**Issue by mbaeuerle** [elixir-lang/flow#25]
In https://github.com/elixir-lang/flow/blob/master/lib/flow.ex#L256 there is a nonexistent link to `GenStage.async_notify/2`. Has this behavior changed?

**Comment by josevalim** [comment]
Yes, thank you. I will change it accordingly.

**Comment by josevalim** [comment]
Fixed in 991a703d70ffdf3755760a6e70c1d28bce1a28c1.

**Comment by mbaeuerle** [comment]
I just found out that there is another place where it is referenced: https://github.com/elixir-lang/flow/blob/991a703d70ffdf3755760a6e70c1d28bce1a28c1/lib/flow.ex#L554

**Comment by josevalim** [comment]
AWesome, fixed that one too. :)
