### ISSUE TITLE
Sliding Window implementation

### ISSUE THREAD

**Issue by leifg** [elixir-lang/flow#26]
It seems like in the test there is use of a [sliding window](https://github.com/elixir-lang/flow/blob/v0.12.0/test/flow/window_test.exs#L32) already.

Would be really cool to have an implementation of that in flow directly.

```
Flow.Window.sliding(count: 2, overlap: 1)
```

I'd be happy to implement it if there is need.

**Comment by josevalim** [comment]
Yes, please. We should probably call it SlidingEventWindow though as it slides on events and not on time.

**Comment by leifg** [comment]
OK great, I will get to it.

Name will be?

```
Flow.Window.sliding_event(count: 2, overlap: 1)
```
