### ISSUE TITLE
Expose timeout parameter passed to GenStage.sync_subscribe

### ISSUE THREAD

**Issue by ben-pr-p** [elixir-lang/flow#38]
I'd like to be able to specify a longer timeout than 5000, and I know that this is an option than GenStage accepts.

In addition to :max_demand and :min_demand, could we get a :timeout option that's passed through to GenStage?

**Comment by josevalim** [comment]
Yup, PR please.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ben-pr-p** [comment]
Will this an issue?

https://github.com/elixir-lang/gen_stage/issues/23

**Comment by isaacsanders** [comment]
@ben-pr-p I wrote a PR for this.
