### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by lackac** [elixir-lang/flow#60]
It would be useful to run the Flow test suite against multiple versions of Elixir. A CI setup with Travis could help with that.

Right now it seems Flow and GenStage progress in lockstep which is fine until they both reach 1.0. After that it would be also useful to test Flow against multiple versions of GenStage.

**Comment by lackac** [comment]
Hmm, it looks like there is already some configuration for Travis, but the project is not enabled there. Is it possible this is only a matter of enabling it, @josevalim?

**Comment by lackac** [comment]
I'm currently testing the Travis setup in my own fork, will report back here after I made it work.

**Comment by josevalim** [comment]
Enabled!
